networks:
  containet:
    driver: bridge

services:
  jellyfin:
    image: jellyfin/jellyfin:10.11.6
    container_name: jellyfin
    restart: unless-stopped
    privileged: true
    environment:
      - JELLYFIN_PublishedServerUrl=http://jellyfin.home
      - VIRTUAL_HOST=jellyfin.home
      - VIRTUAL_PORT=8096
      - CERT_NAME=home
    networks:
      - containet
    ports:
      - 8096:8096
    volumes:
      - ./data/jellyfin/config:/config
      - ./external_hdd/data/jellyfin/cache:/cache
      - ./external_hdd/data/ftp/storage/public/downloads/complete/:/media:ro
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
      - /dev/iep
      - /dev/mpp-service
      - /dev/vpu_service
      - /dev/vpu-service
      - /dev/hevc_service
      - /dev/hevc-service
      - /dev/rkvdec
      - /dev/rkvenc
      - /dev/vepu
      - /dev/h265e
    security_opt:
      - systempaths=unconfined
      - apparmor=unconfined

  wg:
    image: ngoduykhanh/wireguard-ui:0.6.2
    container_name: wgui
    restart: unless-stopped
    environment:
      - WGUI_USERNAME=${USER_ACCOUNT}
      - WGUI_PASSWORD=${PASSWORD}
      - VIRTUAL_HOST=wgui.home
      - CERT_NAME=home
    networks:
      - containet
    volumes:
      - ./data/wireguard_ui:/app/db
      - /etc/wireguard:/etc/wireguard

  cnames-generator:
    image: jwilder/docker-gen:0.16.2
    container_name: cnames-generator
    restart: unless-stopped
    networks:
      - containet
    command: -watch -notify-container pihole -notify-signal -1 /etc/docker-gen/templates/cname.tmpl /cname_output/cname_output
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/cname/template:/etc/docker-gen/templates
      - ./data/cname/output:/cname_output

  pihole:
    image: pihole/pihole:2026.02.0
    container_name: pihole
    restart: unless-stopped
    environment:
      - TZ=Europe/Bucharest
      - FTLCONF_dns_upstreams=unbound
      - FTLCONF_webserver_api_password=${PASSWORD}
      - FTLCONF_webserver_port=80
      - FTLCONF_dns_listeningMode=ALL
      - FTLCONF_dns_hostRecord=server.home,10.8.0.1
      - FTLCONF_dns_domain_name=home
      - FTLCONF_misc_privacyLevel=3
      - VIRTUAL_HOST=pihole.home
      - VIRTUAL_PORT=80
      - CERT_NAME=home
    networks:
      - containet
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d
      - ./data/cname/output:/cname_output
      - ./data/pihole-dyn:/pihole-dyn
    cap_add:
      - SYS_NICE
    entrypoint: ["/bin/bash", "/pihole-dyn/pihole-wrapper.sh"]

  unbound:
    image: alpinelinux/unbound:latest
    container_name: unbound
    restart: unless-stopped
    networks:
      - containet
    volumes:
      - ./data/unbound:/etc/unbound/

  certs-generator:
    image: jwilder/docker-gen:0.16.2
    container_name: certs-generator
    restart: unless-stopped
    networks:
      - containet
    command: -watch -notify /certs/generate.sh -notify-container reverse-proxy -notify-signal -1 /etc/docker-gen/templates/certs.tmpl /config/certs.cnf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs-generator/templates:/etc/docker-gen/templates
      - ./data/certs-generator/config:/config
      - ./data/certs:/certs

  reverse-proxy:
    image: nginxproxy/nginx-proxy:1.10
    container_name: reverse-proxy
    restart: unless-stopped
    networks:
      - containet
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/certs:/etc/nginx/certs
      - ./data/reverse-proxy:/etc/nginx/vhost.d

  ftp:
    image: delfer/alpine-ftp-server
    container_name: ftp
    restart: unless-stopped
    environment:
      - USERS=transfer|transfer
      - ADDRESS=10.8.0.1
    ports:
      - 21:21
      - 21000-21010:21000-21010
    networks:
      - containet
    volumes:
      - ./external_hdd/data/ftp/storage:/ftp/transfer

  vaultwarden:
    image: vaultwarden/server:1.35.4
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      - DOMAIN=https://vaultwarden.home
      - VIRTUAL_HOST=vaultwarden.home
      - VIRTUAL_PORT=80
      - CERT_NAME=home
    networks:
      - containet
    volumes:
      - ./data/vaultwarden:/data

  transmission:
    image: lscr.io/linuxserver/transmission:4.0.5
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
      - USER=${USER_ACCOUNT}
      - PASS=${PASSWORD}
      - DOCKER_MODS=linuxserver/mods:transmission-floodui
      - VIRTUAL_HOST=transmission.home
      - VIRTUAL_PORT=9091
      - CERT_NAME=home
    networks:
      - containet
    ports:
      - 51413:51413
    volumes:
      - ./data/transmission:/config
      - ./external_hdd/data/ftp/storage/public/downloads:/downloads

  portainer:
    image: portainer/portainer-ce:2.39.0-linux-arm64
    container_name: portainer
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portainer.home
      - VIRTUAL_PORT=9000
      - CERT_NAME=home
    networks:
      - containet
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data

  duplicati:
    image: duplicati/duplicati:2.2.0.105
    container_name: duplicati
    restart: unless-stopped
    environment:
      - DUPLICATI__WEBSERVICE_PASSWORD=${PASSWORD}
      - DUPLICATI__WEBSERVICE_ALLOWED_HOSTNAMES=duplicati.home
      - VIRTUAL_HOST=duplicati.home
      - VIRTUAL_PORT=8200
      - CERT_NAME=home
    networks:
      - containet
    volumes:
      - ./data:/data
