version: "2.1"

networks:
  containet:
    driver: bridge

services:
  wg:
    image: ngoduykhanh/wireguard-ui:latest
    container_name: wgui
    restart: always
    environment:
      - WGUI_USERNAME=${USER_ACCOUNT}
      - WGUI_PASSWORD=${PASSWORD}
    networks:
      - containet
    volumes:
      - ./data/wireguard_ui:/app/db
      - /etc/wireguard:/etc/wireguard

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    environment:
      - TZ=Europe/Bucharest
      - PIHOLE_DNS_=193.231.252.1;213.154.124.1
      - ServerIP=10.8.0.1
      - WEBPASSWORD=${PASSWORD}
      - WEB_PORT=8080
    network_mode: host
    volumes:
      - ./data/pihole:/etc/pihole
      - ./data/dnsmasq.d:/etc/dnsmasq.d

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    restart: always
    networks:
      - containet
    ports:
      - 80:80
    volumes:
      - ./data/nginx/conf.d:/etc/nginx/conf.d

  flood:
    image: jesec/flood
    container_name: flood
    restart: always
    environment:
      - HOME=/config
    networks:
      - containet
    command: --port 3001
    volumes:
      - ./data/flood:/config

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: always
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Bucharest
    networks:
      - containet
    ports:
      - 51413:51413
    volumes:
      - ./data/transmission:/config
      - ./external_hdd/data/ftp/storage/public/downloads:/downloads
      - ./external_hdd/data/ftp/storage/public/watch:/watch
